//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManager.Models
{
    using System;

    public partial class Device
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Assignee { get; set; }
        public int AssigneeEC { get; set; }
    }
}
